"""球员英文名 → 中文媒体通用译名.

起始数据集，由自动整理脚本持续扩充；查询逻辑见 zh/__init__.py 的 player_zh()。
"""

from __future__ import annotations

PLAYER_ZH: dict[str, str] = {
    # ===== ATP =====
    "Jannik Sinner": "辛纳",
    "Carlos Alcaraz": "阿尔卡拉斯",
    "Novak Djokovic": "德约科维奇",
    "Alexander Zverev": "兹维列夫",
    "Daniil Medvedev": "梅德韦杰夫",
    "Andrey Rublev": "卢布列夫",
    "Casper Ruud": "鲁德",
    "Taylor Fritz": "弗里茨",
    "Alex de Minaur": "德米纳尔",
    "Stefanos Tsitsipas": "西西帕斯",
    "Grigor Dimitrov": "迪米特洛夫",
    "Tommy Paul": "保罗",
    "Ben Shelton": "谢尔顿",
    "Hubert Hurkacz": "胡尔卡奇",
    "Holger Rune": "鲁内",
    "Frances Tiafoe": "蒂亚福",
    "Karen Khachanov": "哈恰诺夫",
    "Sebastian Korda": "科达",
    "Felix Auger-Aliassime": "阿利亚西姆",
    "Arthur Fils": "菲斯",
    "Jack Draper": "德雷珀",
    "Lorenzo Musetti": "穆塞蒂",
    "Ugo Humbert": "安贝尔",
    "Alexander Bublik": "布勃利克",
    "Francisco Cerundolo": "塞伦多洛",
    "Nicolas Jarry": "哈里",
    "Alejandro Tabilo": "塔比洛",
    "Matteo Berrettini": "贝雷蒂尼",
    "Stan Wawrinka": "瓦林卡",
    "Gael Monfils": "孟菲尔斯",
    "Zhizhen Zhang": "张之臻",
    "Juncheng Shang": "商竣程",
    "Yunchaokete Bu": "布云朝克特",
    "Yibing Wu": "吴易昺",
    # ===== WTA =====
    "Aryna Sabalenka": "萨巴伦卡",
    "Iga Swiatek": "斯瓦泰克",
    "Coco Gauff": "高芙",
    "Elena Rybakina": "莱巴金娜",
    "Jessica Pegula": "佩古拉",
    "Jasmine Paolini": "保利尼",
    "Qinwen Zheng": "郑钦文",
    "Emma Navarro": "纳瓦罗",
    "Daria Kasatkina": "卡萨金娜",
    "Barbora Krejcikova": "克雷吉茨科娃",
    "Danielle Collins": "柯林斯",
    "Madison Keys": "凯斯",
    "Beatriz Haddad Maia": "哈达德·玛雅",
    "Jelena Ostapenko": "奥斯塔彭科",
    "Ons Jabeur": "贾巴尔",
    "Victoria Azarenka": "阿扎伦卡",
    "Naomi Osaka": "大坂直美",
    "Marketa Vondrousova": "万卓索娃",
    "Mirra Andreeva": "米拉·安德列娃",
    "Liudmila Samsonova": "萨姆索诺娃",
    "Ekaterina Alexandrova": "亚历山德洛娃",
    "Donna Vekic": "维基奇",
    "Elina Svitolina": "斯维托丽娜",
    "Karolina Muchova": "穆霍娃",
    "Diana Shnaider": "施奈德",
    "Anna Kalinskaya": "卡林斯卡娅",
    "Paula Badosa": "巴多萨",
    "Katie Boulter": "博尔特",
    "Emma Raducanu": "拉杜卡努",
    "Xinyu Wang": "王欣瑜",
    "Yue Yuan": "袁悦",
    "Xiyu Wang": "王曦雨",
    "Yafan Wang": "王雅繁",
    "Lin Zhu": "朱琳",
    "Shuai Zhang": "张帅",
}
