"""球员英文名 → 中文媒体通用译名.

由整理脚本生成 + 人工校对；查询逻辑见 zh/__init__.py 的 player_zh()。
"""

from __future__ import annotations

PLAYER_ZH: dict[str, str] = {
    # ===== ATP =====
    "Jannik Sinner": "辛纳",
    "Carlos Alcaraz": "阿尔卡拉斯",
    "Alexander Zverev": "兹维列夫",
    "Novak Djokovic": "德约科维奇",
    "Felix Auger-Aliassime": "奥热-阿利亚西姆",
    "Alex de Minaur": "德米纳尔",
    "Ben Shelton": "谢尔顿",
    "Taylor Fritz": "弗里茨",
    "Daniil Medvedev": "梅德韦杰夫",
    "Flavio Cobolli": "科博利",
    "Lorenzo Musetti": "穆塞蒂",
    "Alexander Bublik": "布勃利克",
    "Casper Ruud": "鲁德",
    "Andrey Rublev": "卢布列夫",
    "Jiri Lehecka": "莱赫奇卡",
    "Luciano Darderi": "达尔代里",
    "Learner Tien": "蒂恩",
    "Jakub Mensik": "门西克",
    "Frances Tiafoe": "蒂亚福",
    "Valentin Vacherot": "瓦舍罗",
    "Francisco Cerundolo": "塞伦多洛",
    "Arthur Fils": "菲斯",
    "Tommy Paul": "保罗",
    "Rafael Jodar": "霍达尔",
    "Karen Khachanov": "哈恰诺夫",
    "Jack Draper": "德雷珀",
    "Holger Rune": "鲁内",
    "Joao Fonseca": "丰塞卡",
    "Stefanos Tsitsipas": "西西帕斯",
    "Grigor Dimitrov": "迪米特洛夫",
    "Tomas Machac": "马哈奇",
    "Alejandro Davidovich Fokina": "达维多维奇·福基纳",
    "Denis Shapovalov": "沙波瓦洛夫",
    "Alexei Popyrin": "波皮林",
    "Alex Michelsen": "米切尔森",
    "Ugo Humbert": "安贝尔",
    "Giovanni Mpetshi Perricard": "佩里卡尔",
    "Tallon Griekspoor": "格里克斯普尔",
    "Matteo Berrettini": "贝雷蒂尼",
    "Alexander Shevchenko": "舍甫琴科",
    "Gabriel Diallo": "迪亚洛",
    "Matteo Arnaldi": "阿尔纳尔迪",
    "Luca Nardi": "纳尔迪",
    "Lorenzo Sonego": "索内戈",
    "Mattia Bellucci": "贝卢奇",
    "Arthur Rinderknech": "林德克内希",
    "Terence Atmane": "阿特马内",
    "Cameron Norrie": "诺里",
    "Benjamin Bonzi": "邦齐",
    "Alexandre Muller": "米勒",
    "Corentin Moutet": "穆泰",
    "Valentin Royer": "鲁瓦耶",
    "Arthur Cazaux": "卡佐",
    "Quentin Halys": "阿利斯",
    "Hugo Gaston": "加斯东",
    "Adrian Mannarino": "马纳里诺",
    "Gael Monfils": "孟菲尔斯",
    "Luca Van Assche": "范阿舍",
    "Sebastian Korda": "科达",
    "Brandon Nakashima": "纳卡什马",
    "Reilly Opelka": "奥佩尔卡",
    "Marcos Giron": "吉隆",
    "Nishesh Basavareddy": "巴萨瓦雷迪",
    "Tristan Boyer": "博耶",
    "Ethan Quinn": "奎因",
    "Aleksandar Kovacevic": "科瓦切维奇",
    "Jenson Brooksby": "布鲁克斯比",
    "Emilio Nava": "纳瓦",
    "Colton Smith": "科尔顿·史密斯",
    "Mackenzie McDonald": "麦克唐纳",
    "Christopher Eubanks": "尤班克斯",
    "Jordan Thompson": "汤普森",
    "Christopher O'Connell": "奥康奈尔",
    "James Duckworth": "达克沃斯",
    "Adam Walton": "沃尔顿",
    "Aleksandar Vukic": "武基奇",
    "Rinky Hijikata": "土方凛辉",
    "Tristan Schoolkate": "斯库尔凯特",
    "Nick Kyrgios": "克耶高斯",
    "Bernard Tomic": "托米奇",
    "Roman Safiullin": "萨菲乌林",
    "Jan-Lennard Struff": "斯特鲁夫",
    "Daniel Altmaier": "阿尔特迈尔",
    "Yannick Hanfmann": "汉夫曼",
    "Justin Engel": "恩格尔",
    "Dominik Koepfer": "克普费尔",
    "Jaume Munar": "穆纳尔",
    "Pedro Martinez": "马丁内斯",
    "Roberto Carballes Baena": "卡巴列斯·巴埃纳",
    "Roberto Bautista Agut": "巴蒂斯塔·阿古特",
    "Pablo Carreno Busta": "卡雷尼奥·布斯塔",
    "Martin Landaluce": "兰达卢塞",
    "Jacob Fearnley": "弗恩利",
    "Dan Evans": "埃文斯",
    "Arthur Fery": "费里",
    "Botic van de Zandschulp": "范德赞德舒尔普",
    "Jesper de Jong": "德容",
    "David Goffin": "戈芬",
    "Zizou Bergs": "贝尔格斯",
    "Raphael Collignon": "科利尼翁",
    "Alexander Blockx": "布洛克斯",
    "Stan Wawrinka": "瓦林卡",
    "Dominic Stricker": "施特里克",
    "Sebastian Ofner": "奥夫纳",
    "Filip Misolic": "米索利奇",
    "Marin Cilic": "西里奇",
    "Borna Coric": "丘里奇",
    "Dino Prizmic": "普里兹米奇",
    "Damir Dzumhur": "朱姆胡尔",
    "Laslo Djere": "杰雷",
    "Miomir Kecmanovic": "凯茨马诺维奇",
    "Dusan Lajovic": "拉约维奇",
    "Hamad Medjedovic": "梅杰多维奇",
    "Marton Fucsovics": "富乔维奇",
    "Fabian Marozsan": "马罗赞",
    "Hubert Hurkacz": "胡尔卡奇",
    "Kamil Majchrzak": "迈赫扎克",
    "Vit Kopriva": "科普日瓦",
    "Dalibor Svrcina": "斯弗尔奇纳",
    "Elmer Moller": "默勒",
    "Nuno Borges": "博尔热斯",
    "Jaime Faria": "法里亚",
    "Nicolas Jarry": "哈里",
    "Alejandro Tabilo": "塔比洛",
    "Cristian Garin": "加林",
    "Sebastian Baez": "巴埃斯",
    "Tomas Martin Etcheverry": "埃切维里",
    "Mariano Navone": "纳沃内",
    "Francisco Comesana": "科梅萨尼亚",
    "Camilo Ugo Carabelli": "乌戈·卡拉贝利",
    "Facundo Diaz Acosta": "迪亚斯·阿科斯塔",
    "Roman Burruchaga": "布鲁查加",
    "Thiago Seyboth Wild": "塞博特·维尔德",
    "Thiago Monteiro": "蒙泰罗",
    "Ignacio Buse": "布塞",
    "Daniel Elahi Galan": "加兰",
    "Nikoloz Basilashvili": "巴西拉什维利",
    "Emil Ruusuvuori": "鲁苏武里",
    "Milos Raonic": "拉奥尼奇",
    "Federico Cina": "奇纳",
    "Matteo Gigante": "吉甘特",
    "Francesco Passaro": "帕萨罗",
    "Kei Nishikori": "锦织圭",
    "Yoshihito Nishioka": "西冈良仁",
    "Shintaro Mochizuki": "望月慎太郎",
    "Taro Daniel": "丹尼尔太郎",
    "Yosuke Watanuki": "绵贯阳介",
    "Soonwoo Kwon": "权纯雨",
    "Sumit Nagal": "纳加尔",
    "Chun-Hsin Tseng": "曾俊欣",
    "Coleman Wong": "黄泽林",
    "Zhizhen Zhang": "张之臻",
    "Juncheng Shang": "商竣程",
    "Yunchaokete Bu": "布云朝克特",
    "Yibing Wu": "吴易昺",
    "Yi Zhou": "周意",
    "Fajing Sun": "孙发京",
    # ===== WTA =====
    "Aryna Sabalenka": "萨巴伦卡",
    "Iga Swiatek": "斯瓦泰克",
    "Elena Rybakina": "莱巴金娜",
    "Coco Gauff": "高芙",
    "Jessica Pegula": "佩古拉",
    "Amanda Anisimova": "阿尼西莫娃",
    "Mirra Andreeva": "米拉·安德烈耶娃",
    "Madison Keys": "凯斯",
    "Jasmine Paolini": "保利尼",
    "Ekaterina Alexandrova": "亚历山德罗娃",
    "Karolina Muchova": "穆霍娃",
    "Linda Noskova": "诺斯科娃",
    "Clara Tauson": "陶森",
    "Elina Svitolina": "斯维托丽娜",
    "Naomi Osaka": "大坂直美",
    "Belinda Bencic": "本西奇",
    "Liudmila Samsonova": "萨姆索诺娃",
    "Jelena Ostapenko": "奥斯塔彭科",
    "Victoria Mboko": "姆博科",
    "Diana Shnaider": "施奈德",
    "Emma Navarro": "纳瓦罗",
    "Daria Kasatkina": "卡萨金娜",
    "Beatriz Haddad Maia": "哈达德·玛雅",
    "Elise Mertens": "梅尔滕斯",
    "Sofia Kenin": "肯宁",
    "Emma Raducanu": "拉杜卡努",
    "Marta Kostyuk": "科斯秋克",
    "Dayana Yastremska": "亚斯特雷姆斯卡",
    "Barbora Krejcikova": "克雷吉茨科娃",
    "Veronika Kudermetova": "维罗妮卡·库德梅托娃",
    "Anna Kalinskaya": "卡林斯卡娅",
    "Leylah Fernandez": "费尔南德斯",
    "Maya Joint": "乔因特",
    "Iva Jovic": "约维奇",
    "Ashlyn Krueger": "克鲁格",
    "McCartney Kessler": "凯斯勒",
    "Marketa Vondrousova": "万卓索娃",
    "Paula Badosa": "巴多萨",
    "Donna Vekic": "维基奇",
    "Danielle Collins": "柯林斯",
    "Magdalena Frech": "弗雷赫",
    "Magda Linette": "林内特",
    "Maja Chwalinska": "赫瓦林斯卡",
    "Olga Danilovic": "达尼洛维奇",
    "Alexandra Eala": "埃亚拉",
    "Lois Boisson": "布瓦松",
    "Janice Tjen": "曾丽美",
    "Qinwen Zheng": "郑钦文",
    "Xinyu Wang": "王欣瑜",
    "Shuai Zhang": "张帅",
    "Xiyu Wang": "王曦雨",
    "Yue Yuan": "袁悦",
    "Lin Zhu": "朱琳",
    "Yafan Wang": "王雅繁",
    "Sijia Wei": "韦思佳",
    "Xinyu Gao": "高馨妤",
    "Saisai Zheng": "郑赛赛",
    "Xinyun Han": "韩馨蕴",
    "Zhaoxuan Yang": "杨钊煊",
    "Xinyu Jiang": "蒋欣玗",
    "Qianhui Tang": "汤千慧",
    "Feng Shuo": "冯硕",
    # ESPN 数据源把她的名字拆成三段（姓 Ye + 名 Qiu/Yu 各占一段），
    # 与本文件"名 姓"两段式惯例不同，需按源字符串原样收录才能命中。
    "Ye Qiu Yu": "叶秋语",
    "Hanyu Guo": "郭涵煜",
    "Yifan Xu": "徐一璠",
    "Yexin Ma": "马烨欣",
    "Xinran Sun": "孙心然",
    "Su-Wei Hsieh": "谢淑薇",
    "Fang-Hsien Wu": "吴芳娴",
    "Hao-Ching Chan": "詹皓晴",
    "Latisha Chan": "詹咏然",
    "Jaqueline Cristian": "克里斯蒂安",
    "Sorana Cirstea": "科斯蒂亚",
    "Elena-Gabriela Ruse": "鲁塞",
    "Anca Todoni": "托多尼",
    "Irina-Camelia Begu": "贝古",
    "Anastasia Pavlyuchenkova": "帕夫柳琴科娃",
    "Anastasia Potapova": "波塔波娃",
    "Kamilla Rakhimova": "拉希莫娃",
    "Anna Blinkova": "布林科娃",
    "Polina Kudermetova": "波利娜·库德梅托娃",
    "Anastasia Zakharova": "扎哈罗娃",
    "Erika Andreeva": "埃里卡·安德烈耶娃",
    "Oksana Selekhmeteva": "谢列赫梅捷娃",
    "Victoria Azarenka": "阿扎伦卡",
    "Aliaksandra Sasnovich": "萨斯诺维奇",
    "Yulia Putintseva": "普汀塞娃",
    "Elina Avanesyan": "阿瓦涅相",
    "Rebecca Sramkova": "什拉姆科娃",
    "Anna Karolina Schmiedlova": "施米德洛娃",
    "Viktorija Golubic": "戈卢比奇",
    "Jil Teichmann": "泰希曼",
    "Marie Bouzkova": "鲍兹科娃",
    "Katerina Siniakova": "西尼亚科娃",
    "Tereza Valentova": "瓦伦托娃",
    "Sara Bejlek": "贝莱克",
    "Laura Samson": "萨姆森",
    "Linda Fruhvirtova": "琳达·弗鲁维尔托娃",
    "Petra Kvitova": "科维托娃",
    "Kimberly Birrell": "比勒尔",
    "Ajla Tomljanovic": "汤姆贾诺维奇",
    "Talia Gibson": "吉布森",
    "Priscilla Hon": "韩天遇",
    "Emerson Jones": "埃默生·琼斯",
    "Katie Boulter": "布尔特",
    "Sonay Kartal": "卡尔塔尔",
    "Francesca Jones": "弗朗西斯卡·琼斯",
    "Peyton Stearns": "斯特恩斯",
    "Alycia Parks": "帕克斯",
    "Bernarda Pera": "佩拉",
    "Caroline Dolehide": "多勒海德",
    "Taylor Townsend": "汤森德",
    "Hailey Baptiste": "巴普蒂斯特",
    "Ann Li": "安·李",
    "Katie Volynets": "沃利内茨",
    "Robin Montgomery": "蒙哥马利",
    "Venus Williams": "大威廉姆斯",
    "Varvara Gracheva": "格拉乔娃",
    "Diane Parry": "帕里",
    "Elsa Jacquemot": "雅克莫",
    "Caroline Garcia": "加西亚",
    "Kristina Mladenovic": "姆拉德诺维奇",
    "Laura Siegemund": "西格蒙德",
    "Tatjana Maria": "玛丽亚",
    "Eva Lys": "利斯",
    "Jule Niemeier": "尼迈尔",
    "Ella Seidel": "赛德尔",
    "Cristina Bucsa": "布克沙",
    "Jessica Bouzas Maneiro": "博萨斯·马内罗",
    "Sara Sorribes Tormo": "索里贝斯·托尔莫",
    "Lucia Bronzetti": "布龙泽蒂",
    "Elisabetta Cocciaretto": "科恰雷托",
    "Sara Errani": "埃拉尼",
    "Camila Osorio": "奥索里奥",
    "Emiliana Arango": "阿朗戈",
    "Renata Zarazua": "萨拉苏亚",
    "Solana Sierra": "谢拉",
    "Suzan Lamens": "拉门斯",
    "Arantxa Rus": "鲁斯",
    "Greet Minnen": "米宁",
    "Anna Bondar": "邦达尔",
    "Dalma Galfi": "加尔菲",
    "Viktoriya Tomova": "托莫娃",
    "Tamara Zidansek": "齐丹舍克",
    "Antonia Ruzic": "鲁日奇",
    "Zeynep Sonmez": "森梅兹",
    "Mayar Sherif": "谢里夫",
    "Maria Sakkari": "萨卡里",
    "Anhelina Kalinina": "卡利尼娜",
    "Yuliia Starodubtseva": "斯塔罗杜布采娃",
    "Daria Snigur": "斯尼古尔",
    "Moyuka Uchijima": "内岛萌夏",
    "Aoi Ito": "伊藤葵",
    "Nao Hibino": "日比野菜绪",
    "Ena Shibahara": "柴原瑛菜",
    "Wakana Sonobe": "园部八奏",
    "Bianca Andreescu": "安德莱斯库",
    "Marina Stakusic": "斯塔库西奇",
    "Gabriela Dabrowski": "达布罗夫斯基",
    "Lulu Sun": "孙璐璐",
    "Erin Routliffe": "劳特利夫",
    "Ons Jabeur": "贾巴尔",
    "Simona Halep": "哈勒普",
    # ===== 补充批次：巡回赛常客 / 挑战赛升组球员（新华社式音译） =====
    # ATP
    "Alex Molcan": "莫尔坎",
    "Andrea Pellegrino": "佩莱格里诺",
    "Marco Trungelliti": "特伦杰利蒂",
    "Daniel Merida": "梅里达",
    "Titouan Droguet": "德罗盖",
    "Stefano Travaglia": "特拉瓦利亚",
    "Adolfo Daniel Vallejo": "巴列霍",
    "Hugo Dellien": "德利恩",
    "Federico Coria": "科里亚",
    "Albert Ramos-Vinolas": "拉莫斯-维尼奥拉斯",
    "Otto Virtanen": "维尔塔宁",
    "August Holmgren": "霍尔姆格伦",
    "Tomas Barrios Vera": "巴里奥斯·贝拉",
    "Juan Manuel Cerundolo": "胡安·塞伦多洛",
    "Harold Mayot": "马约",
    "Pierre-Hugues Herbert": "赫伯特",
    "Gregoire Barrere": "巴雷尔",
    "Kyrian Jacquet": "雅凯",
    # WTA
    "Vendula Valdmannova": "瓦尔德曼诺娃",
    "Alina Korneeva": "科尔涅娃",
    "Clara Burel": "布雷尔",
    "Elena Micic": "米契奇",
    "Gina Feistel": "费斯特尔",
    "Lilli Tagger": "塔格尔",
    "Lisa Pigato": "皮加托",
    "Claire Liu": "刘婧文",
    "Nikola Bartunkova": "巴尔通科娃",
    "Barbora Palicova": "帕利佐娃",
    "Dominika Salkova": "沙尔科娃",
    "Darja Vidmanova": "维德曼诺娃",
    "Julia Grabher": "格拉布赫尔",
    "Sinja Kraus": "克劳斯",
    "Panna Udvardy": "乌德瓦尔迪",
    "Celine Naef": "内夫",
    "Simona Waltert": "瓦尔特特",
    "Katarzyna Kawa": "卡瓦",
    "Linda Klimovicova": "克利莫维乔娃",
    "Anastasia Tikhonova": "吉洪诺娃",
    "Maria Timofeeva": "季莫费耶娃",
    "Victoria Jimenez Kasintseva": "希门尼斯·卡辛采娃",
    "Marina Bassols Ribera": "巴索尔斯·里韦拉",
    "Leyre Romero Gormaz": "罗梅罗·戈尔马斯",
    "Nuria Parrizas Diaz": "帕里萨斯·迪亚斯",
    "Tyra Caterina Grant": "格兰特",
    "Julia Riera": "里埃拉",
    "Nuria Brancaccio": "布兰卡乔",
    "Georgia Pedone": "佩多内",
}
