"""赛事英文名 → 中文名与级别.

由整理脚本生成 + 人工校对。key 统一小写包含匹配。
级别代码：GS / M1000 / W1000 / 500 / W500 / 250 / W250 / Finals / TeamCup，
合办站用 "/" 组合（如 "500/W500" 表示 ATP500+WTA500），按 tour 解析。
"""

from __future__ import annotations

# 英文关键词（小写）→ 中文名
TOURNAMENT_ZH: dict[str, str] = {
    "'s-hertogenbosch": "斯海尔托亨博斯草地赛",
    "abierto mexicano telcel": "墨西哥公开赛",
    "abn amro open": "鹿特丹公开赛",
    "abu dhabi": "阿布扎比公开赛",
    "acapulco": "阿卡普尔科站",
    "adelaide": "阿德莱德站",
    "adelaide international": "阿德莱德国际赛",
    "almaty": "阿拉木图公开赛",
    "almaty open": "阿拉木图公开赛",
    "antwerp": "安特卫普站",
    "argentina open": "阿根廷公开赛",
    "asb classic": "ASB经典赛",
    "athens": "雅典公开赛",
    "atlanta": "亚特兰大站",
    "atp finals": "ATP年终总决赛",
    "atx open": "ATX公开赛",
    "auckland": "奥克兰站",
    "austin": "奥斯汀公开赛",
    "australian open": "澳大利亚网球公开赛",
    "bad homburg": "巴特洪堡站",
    "bad homburg open": "巴特洪堡公开赛",
    "barcelona": "巴塞罗那站",
    "barcelona open": "巴塞罗那公开赛",
    "basel": "巴塞尔站",
    "bastad": "巴斯塔德站",
    "beijing": "中国网球公开赛",
    "berlin": "柏林网球公开赛",
    "berlin tennis open": "柏林网球公开赛",
    "billie jean king cup": "比利·简·金杯",
    "billie jean king cup finals": "比利·简·金杯总决赛",
    "birmingham": "伯明翰站",
    "bmw open": "宝马公开赛",
    "bnp paribas nordic open": "斯德哥尔摩公开赛",
    "bnp paribas open": "印第安维尔斯站",
    "bogota": "波哥大公开赛",
    "boss open": "斯图加特公开赛",
    "brisbane": "布里斯班站",
    "brisbane international": "布里斯班国际赛",
    "brussels": "布鲁塞尔站",
    "bucharest": "布加勒斯特公开赛",
    "buenos aires": "阿根廷公开赛",
    "canadian open": "加拿大站",
    "charleston": "查尔斯顿站",
    "charleston open": "查尔斯顿公开赛",
    "chengdu": "成都站",
    "chengdu open": "成都公开赛",
    "chile open": "智利公开赛",
    "china open": "中国网球公开赛",
    "cincinnati": "辛辛那提站",
    "cincinnati open": "辛辛那提公开赛",
    "citi open": "花旗公开赛",
    "cleveland": "克利夫兰站",
    "cluj-napoca": "克卢日-纳波卡站",
    "copa colsanitas": "波哥大公开赛",
    "credit one charleston open": "查尔斯顿公开赛",
    "croatia open": "克罗地亚公开赛",
    "dallas": "达拉斯公开赛",
    "dallas open": "达拉斯公开赛",
    "davis cup": "戴维斯杯",
    "davis cup finals": "戴维斯杯总决赛",
    "dc open": "华盛顿公开赛",
    "delray beach": "德尔雷海滩公开赛",
    "delray beach open": "德尔雷海滩公开赛",
    "doha": "多哈站",
    "dubai": "迪拜站",
    "dubai duty free tennis championships": "迪拜免税店网球锦标赛",
    "eastbourne": "伊斯特本站",
    "erste bank open": "维也纳公开赛",
    "estoril": "埃斯托利尔公开赛",
    "estoril open": "埃斯托利尔公开赛",
    "european open": "欧洲公开赛",
    "french open": "法国网球公开赛",
    "generali open": "基茨比厄尔公开赛",
    "geneva": "日内瓦公开赛",
    "geneva open": "日内瓦公开赛",
    "grand prix hassan ii": "哈桑二世大奖赛",
    "gstaad": "格施塔德站",
    "guadalajara": "瓜达拉哈拉站",
    "guadalajara open": "瓜达拉哈拉公开赛",
    "guangzhou": "广州站",
    "guangzhou open": "广州国际女子网球公开赛",
    "halle": "哈雷站",
    "hamburg": "汉堡站",
    "hamburg open": "汉堡公开赛",
    "hangzhou": "杭州站",
    "hangzhou open": "杭州公开赛",
    "hellenic championship": "希腊锦标赛",
    "hobart": "霍巴特国际赛",
    "hobart international": "霍巴特国际赛",
    "hong kong": "中国香港站",
    "hong kong open": "香港网球公开赛",
    "houston": "休斯敦公开赛",
    "hsbc championships": "女王杯",
    "hua hin": "华欣公开赛",
    "iasi": "雅西站",
    "iasi open": "雅西公开赛",
    "indian wells": "印第安维尔斯站",
    "internationaux de strasbourg": "斯特拉斯堡国际赛",
    "internazionali": "罗马站",
    "internazionali bnl d'italia": "意大利公开赛",
    "italian open": "罗马站",
    "japan open": "日本公开赛",
    "japan women's open": "日本女子公开赛",
    "jasmin open": "茉莉公开赛",
    "jiangxi open": "江西网球公开赛",
    "jiujiang": "江西网球公开赛",
    "kinoshita group japan open": "日本公开赛",
    "kitzbuhel": "基茨比厄尔站",
    "kitzbühel": "基茨比厄尔公开赛",
    "korea open": "韩国公开赛",
    "laver cup": "拉沃尔杯",
    "lexus eastbourne open": "伊斯特本国际赛",
    "libema open": "利贝马公开赛",
    "linz": "林茨站",
    "los cabos": "洛斯卡沃斯站",
    "los cabos open": "洛斯卡沃斯公开赛",
    "madrid": "马德里公开赛",
    "madrid open": "马德里站",
    "mallorca": "马略卡锦标赛",
    "mallorca championships": "马略卡锦标赛",
    "marrakech": "马拉喀什大奖赛",
    "marseille": "马赛站",
    "merida": "梅里达公开赛",
    "merida open": "梅里达公开赛",
    "metz": "梅斯站",
    "mexican open": "墨西哥公开赛",
    "miami": "迈阿密大师赛",
    "miami open": "迈阿密站",
    "monastir": "莫纳斯蒂尔公开赛",
    "monte carlo": "蒙特卡洛大师赛",
    "monte-carlo": "蒙特卡洛大师赛",
    "monte-carlo masters": "蒙特卡洛大师赛",
    "monterrey": "蒙特雷站",
    "monterrey open": "蒙特雷公开赛",
    "montpellier": "蒙彼利埃站",
    "montreal": "蒙特利尔站",
    "morocco open": "摩洛哥公开赛",
    "mubadala abu dhabi open": "阿布扎比公开赛",
    "mubadala citi dc open": "华盛顿公开赛",
    "munich": "慕尼黑公开赛",
    "mutua madrid": "马德里站",
    "mutua madrid open": "马德里公开赛",
    "national bank open": "加拿大站",
    "newport": "纽波特站",
    "next gen": "新生代总决赛",
    "next gen atp finals": "ATP新生代总决赛",
    "ningbo": "宁波站",
    "ningbo open": "宁波网球公开赛",
    "nitto atp finals": "ATP年终总决赛",
    "nordea open": "瑞典公开赛",
    "nottingham": "诺丁汉站",
    "nottingham open": "诺丁汉公开赛",
    "open 13": "马赛公开赛",
    "open de rouen": "鲁昂公开赛",
    "open occitanie": "蒙彼利埃公开赛",
    "osaka": "大阪站",
    "ostrava": "俄斯特拉发站",
    "palermo": "巴勒莫站",
    "palermo ladies open": "巴勒莫女子公开赛",
    "pan pacific open": "泛太平洋公开赛",
    "paris": "巴黎大师赛",
    "paris masters": "巴黎大师赛",
    "porsche tennis grand prix": "保时捷大奖赛",
    "prague": "布拉格站",
    "prague open": "布拉格公开赛",
    "qatar": "多哈站",
    "qatar exxonmobil open": "卡塔尔公开赛",
    "qatar open": "卡塔尔公开赛",
    "qatar totalenergies open": "卡塔尔公开赛",
    "queen's club": "女王杯",
    "queens club": "女王杯",
    "rabat": "拉巴特公开赛",
    "rio de janeiro": "里约公开赛",
    "rio open": "里约站",
    "roland garros": "法国网球公开赛",
    "roland-garros": "法国网球公开赛",
    "rolex monte-carlo masters": "蒙特卡洛大师赛",
    "rolex paris": "巴黎大师赛",
    "rolex paris masters": "巴黎劳力士大师赛",
    "rolex shanghai masters": "上海劳力士大师赛",
    "rome": "罗马站",
    "rotterdam": "鹿特丹站",
    "rouen": "鲁昂公开赛",
    "santiago": "智利公开赛",
    "sao paulo": "圣保罗公开赛",
    "seoul": "首尔站",
    "shanghai": "上海大师赛",
    "shanghai masters": "上海大师赛",
    "singapore": "新加坡网球公开赛",
    "singapore tennis open": "新加坡网球公开赛",
    "sp open": "圣保罗公开赛",
    "stockholm": "斯德哥尔摩站",
    "stockholm open": "斯德哥尔摩公开赛",
    "strasbourg": "斯特拉斯堡站",
    "stuttgart": "斯图加特站",
    "swedish open": "瑞典公开赛",
    "swiss indoors": "瑞士室内网球赛",
    "swiss open gstaad": "瑞士公开赛",
    "tennis in the land": "克利夫兰公开赛",
    "terra wortmann open": "哈雷公开赛",
    "thailand open": "泰国公开赛",
    "the championships, wimbledon": "温布尔登网球锦标赛",
    "tiriac open": "蒂里亚克公开赛",
    "tokyo": "东京站",
    "toray pan pacific open": "东丽泛太平洋公开赛",
    "toronto": "多伦多站",
    "transylvania open": "特兰西瓦尼亚公开赛",
    "umag": "乌马格站",
    "united cup": "联合杯",
    "upper austria ladies linz": "林茨公开赛",
    "us men's clay court championship": "美国男子红土锦标赛",
    "us open": "美国网球公开赛",
    "us open tennis championships": "美国网球公开赛",
    "vienna": "维也纳站",
    "washington": "华盛顿站",
    "western & southern open": "辛辛那提公开赛",
    "wimbledon": "温布尔登网球锦标赛",
    "winston-salem": "温斯顿-塞勒姆站",
    "winston-salem open": "温斯顿-塞勒姆公开赛",
    "wta finals": "WTA年终总决赛",
    "wta finals riyadh": "WTA年终总决赛",
    "wuhan": "武汉网球公开赛",
    "wuhan open": "武汉网球公开赛",
}

# 英文关键词（小写）→ 级别代码
TOURNAMENT_LEVEL: dict[str, str] = {
    "'s-hertogenbosch": "250/W250",
    "abierto mexicano telcel": "500",
    "abn amro open": "500",
    "abu dhabi": "W500",
    "acapulco": "500",
    "adelaide": "250/W500",
    "adelaide international": "250/W500",
    "almaty": "250",
    "almaty open": "250",
    "argentina open": "250",
    "asb classic": "250/W250",
    "athens": "250",
    "atp finals": "Finals",
    "atx open": "W250",
    "auckland": "250/W250",
    "austin": "W250",
    "australian open": "GS",
    "bad homburg": "W500",
    "bad homburg open": "W500",
    "barcelona": "500",
    "barcelona open": "500",
    "basel": "500",
    "bastad": "250",
    "beijing": "W1000/500",
    "berlin": "W500",
    "berlin tennis open": "W500",
    "billie jean king cup": "TeamCup",
    "billie jean king cup finals": "TeamCup",
    "bmw open": "500",
    "bnp paribas nordic open": "250",
    "bnp paribas open": "M1000/W1000",
    "bogota": "W250",
    "boss open": "250",
    "brisbane": "250/W500",
    "brisbane international": "250/W500",
    "brussels": "250",
    "bucharest": "250",
    "buenos aires": "250",
    "canadian open": "M1000/W1000",
    "charleston": "W500",
    "charleston open": "W500",
    "chengdu": "250",
    "chengdu open": "250",
    "chile open": "250",
    "china open": "W1000/500",
    "cincinnati": "M1000/W1000",
    "cincinnati open": "M1000/W1000",
    "citi open": "500/W500",
    "cleveland": "W250",
    "cluj-napoca": "W250",
    "copa colsanitas": "W250",
    "credit one charleston open": "W500",
    "croatia open": "250",
    "dallas": "500",
    "dallas open": "500",
    "davis cup": "TeamCup",
    "davis cup finals": "TeamCup",
    "dc open": "500/W500",
    "delray beach": "250",
    "delray beach open": "250",
    "doha": "W1000/500",
    "dubai": "W1000/500",
    "dubai duty free tennis championships": "W1000/500",
    "eastbourne": "250/W250",
    "erste bank open": "500",
    "estoril": "250",
    "estoril open": "250",
    "european open": "250",
    "french open": "GS",
    "generali open": "250",
    "geneva": "250",
    "geneva open": "250",
    "grand prix hassan ii": "250",
    "gstaad": "250",
    "guadalajara": "W500",
    "guadalajara open": "W500",
    "guangzhou": "W250",
    "guangzhou open": "W250",
    "halle": "500",
    "hamburg": "500",
    "hamburg open": "500",
    "hangzhou": "250",
    "hangzhou open": "250",
    "hellenic championship": "250",
    "hobart": "W250",
    "hobart international": "W250",
    "hong kong": "250",
    "hong kong open": "250",
    "houston": "250",
    "hsbc championships": "500/W500",
    "hua hin": "W250",
    "iasi": "W250",
    "iasi open": "W250",
    "indian wells": "M1000/W1000",
    "internationaux de strasbourg": "W500",
    "internazionali bnl d'italia": "M1000/W1000",
    "italian open": "M1000/W1000",
    "japan open": "500",
    "japan women's open": "W250",
    "jasmin open": "W250",
    "jiangxi open": "W250",
    "jiujiang": "W250",
    "kinoshita group japan open": "500",
    "kitzbuhel": "250",
    "kitzbühel": "250",
    "korea open": "W250",
    "laver cup": "TeamCup",
    "lexus eastbourne open": "250/W250",
    "libema open": "250/W250",
    "linz": "W500",
    "los cabos": "250",
    "los cabos open": "250",
    "madrid": "M1000/W1000",
    "madrid open": "M1000/W1000",
    "mallorca": "250",
    "mallorca championships": "250",
    "marrakech": "250",
    "marseille": "250",
    "merida": "W500",
    "merida open": "W500",
    "mexican open": "500",
    "miami": "M1000/W1000",
    "miami open": "M1000/W1000",
    "monastir": "W250",
    "monte carlo": "M1000",
    "monte-carlo": "M1000",
    "monte-carlo masters": "M1000",
    "monterrey": "W500",
    "monterrey open": "W500",
    "montpellier": "250",
    "montreal": "M1000",
    "morocco open": "W250",
    "mubadala abu dhabi open": "W500",
    "mubadala citi dc open": "500/W500",
    "munich": "500",
    "mutua madrid open": "M1000/W1000",
    "national bank open": "M1000/W1000",
    "next gen atp finals": "Finals",
    "ningbo": "W500",
    "ningbo open": "W500",
    "nitto atp finals": "Finals",
    "nordea open": "250",
    "nottingham": "W250",
    "nottingham open": "W250",
    "open 13": "250",
    "open de rouen": "W250",
    "open occitanie": "250",
    "osaka": "W250",
    "palermo": "W250",
    "palermo ladies open": "W250",
    "pan pacific open": "W500",
    "paris": "M1000",
    "paris masters": "M1000",
    "porsche tennis grand prix": "W500",
    "prague": "W250",
    "prague open": "W250",
    "qatar exxonmobil open": "500",
    "qatar open": "W1000/500",
    "qatar totalenergies open": "W1000",
    "queen's club": "500/W500",
    "queens club": "500/W500",
    "rabat": "W250",
    "rio de janeiro": "500",
    "rio open": "500",
    "roland garros": "GS",
    "roland-garros": "GS",
    "rolex monte-carlo masters": "M1000",
    "rolex paris masters": "M1000",
    "rolex shanghai masters": "M1000",
    "rome": "M1000/W1000",
    "rotterdam": "500",
    "rouen": "W250",
    "santiago": "250",
    "sao paulo": "W250",
    "seoul": "W250",
    "shanghai": "M1000",
    "shanghai masters": "M1000",
    "singapore": "W500",
    "singapore tennis open": "W500",
    "sp open": "W250",
    "stockholm": "250",
    "stockholm open": "250",
    "strasbourg": "W500",
    "stuttgart": "250/W500",
    "swedish open": "250",
    "swiss indoors": "500",
    "swiss open gstaad": "250",
    "tennis in the land": "W250",
    "terra wortmann open": "500",
    "thailand open": "W250",
    "the championships, wimbledon": "GS",
    "tiriac open": "250",
    "tokyo": "500/W500",
    "toray pan pacific open": "W500",
    "toronto": "W1000",
    "transylvania open": "W250",
    "umag": "250",
    "united cup": "TeamCup",
    "upper austria ladies linz": "W500",
    "us men's clay court championship": "250",
    "us open": "GS",
    "us open tennis championships": "GS",
    "vienna": "500",
    "washington": "500/W500",
    "western & southern open": "M1000/W1000",
    "wimbledon": "GS",
    "winston-salem": "250",
    "winston-salem open": "250",
    "wta finals": "Finals",
    "wta finals riyadh": "Finals",
    "wuhan": "W1000",
    "wuhan open": "W1000",
}


def tournament_zh(name: str | None) -> str | None:
    """赛事英文名 → 中文名；未识别时原样返回."""
    if not name:
        return None
    key = name.strip().lower()
    for k, v in sorted(TOURNAMENT_ZH.items(), key=lambda kv: -len(kv[0])):
        if k in key:
            return v
    return name


def _resolve_level_token(raw: str, tour: str | None) -> str | None:
    """把 "500/W500"、"M1000/W1000" 这类组合码按巡回赛解析成单一级别."""
    tokens = [t.strip() for t in raw.split("/") if t.strip()]
    if not tokens:
        return None
    both = {"GS", "Finals", "TeamCup"}
    for t in tokens:
        if t in both:
            return t
    atp_token = next(
        (t for t in tokens if t == "M1000" or t.isdigit()), None
    )
    wta_token = next((t for t in tokens if t.startswith("W")), None)
    if tour == "WTA":
        # 严格：ATP 250 合办站的女子赛事可能是 WTA 125，没有 W 码就不认级别
        t = wta_token
    elif tour == "ATP":
        t = atp_token
    else:
        t = atp_token or wta_token
    if t is None:
        return None
    if t == "M1000":
        return "M1000"
    if t.startswith("W"):
        return {"W1000": "W1000", "W500": "WTA500", "W250": "WTA250"}.get(t, t)
    if t.isdigit():
        prefix = "WTA" if tour == "WTA" else "ATP"
        return f"{prefix}{t}"
    return t


def tournament_level(name: str | None, tour: str | None = None) -> str | None:
    """按赛事名推断级别代码；未识别返回 None."""
    if not name:
        return None
    key = name.strip().lower()
    for k, v in sorted(TOURNAMENT_LEVEL.items(), key=lambda kv: -len(kv[0])):
        if k in key:
            return _resolve_level_token(v, tour)
    return None
